### ISSUE TITLE
Question: border and internal-border

### ISSUE THREAD

**Issue by seagle0128** [tumashu/posframe#100]
https://github.com/tumashu/posframe/blob/739d8fd1081bdd0d20dee9e437d64df58747b871/posframe.el#L329

I noticed `border-width` and `border-color` will be overrided by  `internal-border-width` and `internal-border-color`. May I know the reason? I think `internal-border` can be used for paddings of the text area. They are totally different but now we just choose one of them.

**Comment by tumashu** [comment]
时间太长了，我有点记不清了，好像是border不怎么可靠，所以用internal-border, 至于参数选border，当然考虑很简单，就是让posframe显示一个边框，不管用什么办法实现，

**Comment by seagle0128** [comment]
嗯，看代码是这样。只是这样的话`internal-border`就失去意义了，不能作为内部的填充区来使用。你认为是Emacs的bug？

**Comment by tumashu** [comment]
posframe的border要不使用internal-border要不使用child-frame-border, posframe的border和 frame的border是不同的概念

**Comment by seagle0128** [comment]
那有没有办法给文字显示区域加上padding呢？目前只看到fringe可用，上下就没有办法了。

**Comment by tumashu** [comment]
暂时没有，不过你可以研究研究，毕竟我当时写posframe的时候，对frame也是粗浅了解，只不过可能接口兼容比较麻烦，历史原因有时候也没法

**Comment by seagle0128** [comment]
好，我看看还有没有其他办法。谢谢！
