### ISSUE TITLE
posframe crashes emacs

### ISSUE THREAD

**Issue by mbuczko** [tumashu/posframe#107]
I recently noticed that my company completions stopped working when used along with newest posframe - frame with completions does not open and each subsequent keystroke makes emacs "blinking" and finally crashing (see attached video).

Happens on Emacs 27.2 (both Mac & Linux) and still works ok on Emacs 28. I tried to deduce the code causing this behaviour and that led me to this snippet:

```elisp
        ;; HACK: Set face background after border color, otherwise the
        ;; border is not updated (BUG!).
        (when (version< emacs-version "28.0")
          (set-frame-parameter
           posframe--frame 'background-color
           (face-attribute 'default :background posframe--frame)))
```

when commented out - everything works well again (and probably explains why it works on Emacs 28 ;)

https://user-images.githubusercontent.com/586537/139557113-8dba6d80-927f-4c8a-8397-c2cc1a37cb79.mp4

**Comment by tumashu** [comment]
I have tested with emacs 27.2 linux xfce4, and have not found this problem, how do you test in linux?

**Comment by tumashu** [comment]
```
        ;; HACK: Set face background after border color, otherwise the
        ;; border is not updated (BUG!).
        (when (version< emacs-version "28.0")
          (set-frame-parameter
           posframe--frame 'background-color
           (face-attribute 'default :background posframe--frame)))
```

**Comment by mbuczko** [comment]
> Which part can crash emacs in macox? set-frame-parametr or face-attribute?

good question. looks like it's face-attribute. following works perfectly well:

```elisp
(when (version< emacs-version "28.0")
            (set-frame-parameter
             posframe--frame 'background-color "#282c34"))
```

for completeness:
GNU Emacs 27.2 (build 1, x86_64-apple-darwin20.3.0, Carbon Version 164 AppKit 2022.3) of 2021-03-31

build from brew's railwaycat/emacsmacport/emacs-mac emacs-27.2-mac-8.2

**Comment by mbuczko** [comment]
> I have tested with emacs 27.2 linux xfce4, and have not found this problem, how do you test in linux?

Emacs installed from Ubuntu's Snap Store:
![Screenshot from 2021-10-31 18-48-07](https://user-images.githubusercontent.com/586537/139595676-c3cd97e5-fa1e-45d6-9108-951d8d22e8b7.png)

Modes enabled:

```
Abbrev Async-Bytecomp-Package Auto-Compile Auto-Compile-On-Save Auto-Composition Auto-Compression
Auto-Encryption Blink-Cursor Company Company-Posframe Company-Statistics Cua Delete-Selection Display-Line-Numbers Eldoc
Eldoc-In-Minibuffer Electric-Indent File-Name-Shadow Flycheck Font-Lock Global-Auto-Revert Global-Company
Global-Flycheck Global-Font-Lock Global-Golden Global-Highlight-Parentheses Global-So-Long Helm Highlight-Numbers
Highlight-Parentheses Highlight-Quoted Hl-Line Hl-Todo Line-Number Mouse-Wheel Override-Global Projectile
Rainbow-Delimiters Recentf Save-Place Savehist Shell-Dirtrack Show-Paren Size-Indication Smartparens Smartparens-Global
Smartparens-Global-Strict Smartparens-Strict Solaire Transient-Mark Treemacs-Filewatch Treemacs-Follow
Treemacs-Fringe-Indicator Treemacs-Git Which-Key Window-Divider Window-Numbering Winner Ws-Butler Ws-Butler-Global Yas
```
Basically fails even on bare *scratch* buffer. Works again when replaced `(face-attribute ...)` with actual value.
What's interesting, face-attribute called separately works fine (no crash).

I'm not sure if that's helpful, let me know if I could provide more useful details.

**Comment by tumashu** [comment]
please try https://github.com/tumashu/posframe/commit/8a2bfe9130c7986521fd50619e896346f3027b3a

**Comment by mbuczko** [comment]
it works with company-tooltip background explicitly set up (so the `(face-attribute 'default :background)` part is never called). and that actually solves my problem, though I still have no idea why this expression is able to crash emacs on both platforms :)

anyway, thanks for looking at the problem.

**Comment by tumashu** [comment]
can (face-attribute 'default :background) crash your emacs ？

**Comment by mbuczko** [comment]
and that's the most embarrassing part which I'm not able to explain - evaluated separately works totally fine. as a part of  `(set-frame-parameter ...)` expression grounds my emacs within seconds (on linux too). I see something like this first time to be honest :)

**Comment by tumashu** [comment]
wow...
