### ISSUE TITLE
Mouse not repositioning/banishing when EXWM buffers are behind

### ISSUE THREAD

**Issue by nbarrientos** [tumashu/posframe#108]
Hi,

I've just upgraded posframe to `1.1.0` and I realised that `posframe-mouse-banish` is gone in favor or a simplified and more internal mouse banishing strategy. 

However, it seems though that now if the mouse pointer is placed in the posframe region when a posframe is invoked **and** the buffer in the frame behind is in mode EXWM, then the mouse is not positioned automatically out of the way (it's kept where it was before the posframe shows up).

On the contrary, if the buffer behind is a standard Emacs buffer it works as expected: the pointer is placed out of the way on the top-left corner of the posframe.

I think that when I was setting this:

```lisp
(setq posframe-mouse-banish `(,(frame-width) . 0))
```
to move pointer to the position I wanted, posframe was behaving as expected no matter what was the mode of the buffers behind.

Steps to reproduce:

1) Split your Emacs frame vertically into two windows, the left one showing an EXWM buffer and the right one any regular Emacs buffer. 
2) Configure a posframe so it's created centered and spanning the two windows 50%, like this:

![image](https://user-images.githubusercontent.com/131893/140889889-c449df3e-1dec-492f-8ab5-1014ffb11ef1.png)

3) Place the mouse pointer on the left side of the region (where the EXWM buffer is) in a position that's going to be occupied by the posframe and then invoke it.

* Expected behaviour: the mouse pointer moves to the left-top corner.
* Actual behaviour: the mouse pointer stays where it is :-1:, potentially overlapping with elements in the posframe.

4) Repeat 3) but this time placing the mouse pointer on the right side of the region (where a standard Emacs buffer lives)

* Expected behaviour: the mouse pointer moves to the left-top corner.
* Actual behaviour: the expected one :+1: 

Thanks!

**Comment by tumashu** [comment]
```
Place the mouse pointer on the left side of the region (where the EXWM buffer is) in a position that's going to be occupied by the posframe and then invoke it.
```
what the result of (mouse-position)  in this situation?

**Comment by nbarrientos** [comment]
Hi,

> what the result of (mouse-position) in this situation?

Before the posframe is invoked:

```
(#<frame emacs@the_machines_hostname_here 0x5579ad5e3ab0> nil))
```

After the posframe is displayed (and the mouse pointer over it):

```
(#<frame  0x5579b056f040> 65 . 6))
```

**Comment by nbarrientos** [comment]
If I'm reading the code correctly `posframe--mouse-banish` is not executed in this case. Maybe it makes sense to reposition blindly to the top-left corner if the `(mouse-position)` is not known (switchable with a `defcustom`, perhaps?)

**Comment by nbarrientos** [comment]
If I'm reading the code correctly, `posframe--mouse-banish` [is not executed](https://github.com/tumashu/posframe/blob/c153c288a462e10fc468d7474f0082e6c8f5c527/posframe.el#L682) in this situation. Maybe the mouse could be repositioned bindly if the position is not known (behind a `defcustom`?).

**Comment by tumashu** [comment]
Try (setq posframe-mouse-banish-function #'posframe-mouse-banish-simple)

**Comment by nbarrientos** [comment]
Nice, thanks! It does the job, although I personally prefer to banish it blindly to the top-level corner of the posframe (instead of `(0,0)`). Now I can define my own function which is good enough. I've contributed back the function in case you wanted to include it in the package:

https://github.com/tumashu/posframe/pull/109/

**Comment by tumashu** [comment]
Simple function has been updated. move to posframe's 0，0
