### ISSUE TITLE
去掉本地变量

### ISSUE THREAD

**Issue by et2010** [tumashu/posframe#11]
您指定的编码为utf-8-unix，clone到Windows上默认是crlf行尾，这样会造成clone的文件在emacs中不能正确打开：

![image](https://user-images.githubusercontent.com/11584902/41706605-d02aa9c4-756e-11e8-9c61-7f8ea8a87675.png)

如果只是编辑还好说，问题是用quelpa安装的包如果以posframe作为依赖，就会导致安装失败。 

我觉得编码不如交由git自动管理。用户只要开启了autocrlf（默认开启），在Window和linux平台编辑commit都不会有什么问题。您怎么看？如果可以的话，我就提交一个PR把这个本地变量删除了。

@tumashu

**Comment by tumashu** [comment]
对于 emacs package, 我不认为 "开启了autocrlf" 是一个好事情，
以前我因为编码的问题碰到许多麻烦，所以我所有的packge 都是强制
设置编码的

**Comment by tumashu** [comment]
你这个问题似乎应该在 quelpa 那边得到解决

**Comment by tumashu** [comment]
我在window 上不开autocrlf, emacs 可以自动识别，不需要自动转换

**Comment by et2010** [comment]
关闭 autocrlf 也就是说原样 checkout？

**Comment by et2010** [comment]
编码的问题确实比较蛋疼，您的 yasdcv 在Windows下由于编码的原因也无法使用，我还没有找到具体的原因
