### ISSUE TITLE
Please tag version 1.1.7

### ISSUE THREAD

**Issue by thkoch2001** [tumashu/posframe#112]
I packaged posframe for Debian: https://tracker.debian.org/pkg/emacs-posframe

Could you please tag commit c91d4d53fa479ceb604071008ce0a901770eff57 as version 1.1.7 so that the Debian dashboard is not confused that I packaged a newer version than the last one that is tagged on github?

https://udd.debian.org/dmd/?email1=&email2=&email3=&packages=emacs-posframe&ignpackages=&format=html#versions

Thank you!

**Comment by tumashu** [comment]
Added.
