### ISSUE TITLE
Editing text on a frame

### ISSUE THREAD

**Issue by RadonBurner** [tumashu/posframe#114]
I had a idea to make the scratch buffer pop up for temporary notes using posframe, however when it pop ups it does not allow me to edit the text on the posframe frame itself.

Code:
(defun show-misc-posframe ()
  (interactive)
  (when (posframe-workable-p)
    (posframe-show "*scratch*"
		   :border-color "#ee7b29"
		   :border-width 2
		 :poshandler  'posframe-poshandler-frame-center
		 :height (round(* (frame-height) 0.90))
		 :width (round(* (frame-width) 0.75))
;		 :override-parameters '((cursor-type box))
		 )
    )
   (with-current-buffer "*scratch*"
      (setq-local cursor-type t)
      (setq-local cursor-in-non-selected-windows 'box))
  )

![Screen Shot 2022-06-24 at 7 24 31 pm](https://user-images.githubusercontent.com/79120377/175512388-d0e5bb11-4b29-4111-874d-4041251358dc.png)

**Comment by tumashu** [comment]
Yes, at the moment, posframe do not get focus, so it only can show and can not select and edit.

**Comment by RadonBurner** [comment]
Would there be any workaround to this, if posframe can have focus it would be possible for even a pop up shell.

**Comment by tumashu** [comment]
I do not know more about focus, may be you can read code and try, forcus seem to hard deal with

**Comment by tumashu** [comment]
maybe you should search package list, maybe other package has this feature

**Comment by RadonBurner** [comment]
Is there any temporary workaround

**Comment by zhenhua-wang** [comment]
@RadonBurner It seems you can edit the buffer in posframe by having `:accept-focus t` in `posframe-show`. I don't know if this is correct usage though.

**Comment by RadonBurner** [comment]
@zhenhua-wang Thanks, is there anyway to to show cursor when focusing

**Comment by zhenhua-wang** [comment]
What you did above was correct. You also need to set `:override-parameters '((cursor-type . bar))` inside `posframe-show`.
