### ISSUE TITLE
Refresh position in posframe-refresh

### ISSUE THREAD

**Issue by BlueFlo0d** [tumashu/posframe#117]
Currently if I display a posframe in the center of parent frame, insert something, and call `posframe-refresh`, only child frame size is updated and it's no longer centered.

Is there a way to also recompute its position? I understand that in many case user would want position to instead not change, but maybe an option to update position will be helpful.

**Comment by tumashu** [comment]
why not just use posframe-show, which can let buffer as argument.

**Comment by BlueFlo0d** [comment]
That indeed solves the issue! Sorry for the noise.
