### ISSUE TITLE
Adding support for a Zoom Factor?

### ISSUE THREAD

**Issue by taquangtrung** [tumashu/posframe#121]
Hi,

It would be very nice if `posframe` can support a zoom factor in `posframe-show`:

I'm using [which-key-posframe](https://github.com/yanghaoxie/which-key-posframe), and the default font size is the same as my default font size (small), so it isn't easy to spot some which-key recommendations.

Do you think if  `posframe` can support a zoom factor to increase the font size of some particular posframes?

For example, I want to show `which-key--buffer` with a zoom factor like below:

```emacs-lisp
(posframe-show
         which-key--buffer
         ...
         :position (point)
         :poshandler which-key-posframe-poshandler
         :zoom ...  // Expect to support some zoom factor here
```

Currently, I implemented a quick patch using [zoom-frm](https://www.emacswiki.org/emacs/zoom-frm.el) (this package is not an official Emacs package).

```emacs-lisp
      ;; Create posframe
      (setq posframe
            (posframe--create-posframe
             buffer
             :font font
             ....)

      ;; My new code
      (let ((zoomed (frame-parameter posframe 'zoomed))
            (frame-zoom-font-difference 2))
        (unless zoomed (zoom-frm-in posframe)))
```

Here is the result, where the text in which-key frame is easy to read.

![posframe](https://user-images.githubusercontent.com/193967/210049441-e293b1ff-b40d-4049-9458-7ba1591fd111.png)

**Comment by tumashu** [comment]
What about set a bigger font?

```

(defcustom which-key-posframe-font nil
  "The font used by which-key-posframe.
When nil, Using current frame's font as fallback."
  :group 'which-key-posframe
  :type 'string)
```

**Comment by taquangtrung** [comment]
@tumashu: awesome! I managed to get a similar result using:

```emacs-lisp
(setq which-key-posframe-font
        (font-spec :size 14.0))
```

**Comment by tumashu** [comment]
ok
