### ISSUE TITLE
请问posframe是否可以支持emoji显示？

### ISSUE THREAD

**Issue by dancewhale** [tumashu/posframe#127]
我用的pyim+liberime+rime_ice词库，词库自带很多emoji图标，通过安装emacs-emojify包，已经可以在buffer中显示emoji图标，但是弹出的posframe里面还是一坨方框乱码。

想请教下有没有办法在posframe弹出框中显示emoij图标？

**Comment by tumashu** [comment]
我对 emoji 不太了解，暂时不知道该怎么处理，你可以试试 popup 
```
(require 'popup)
(setq pyim-page-tooltip 'popup)
```
