### ISSUE TITLE
Allow custom setup in childframe buffer

### ISSUE THREAD

**Issue by noctuid** [tumashu/posframe#14]
For example, it should be possible to customize `display-line-numbers` and other variables in the buffer that is created. A new keyword could be added to `posframe-show` to pass in a function to run in the buffer to do this; a keyword specifically for settings to change could also be added.

**Comment by tumashu** [comment]
```
A new keyword could be added to posframe-show to pass in a function to run in the buffer to do this
```
Seem to be a good idea

```
a keyword specifically for settings to change could also be added.
```
what does this mean?

**Comment by noctuid** [comment]
For example, `:set '(var val var val...)` or `:let '((var val)...)`. Instead of passing in a function, you'd pass in a quoted list of settings to make in the buffer.

**Comment by tumashu** [comment]
maybe a :eval can do all the job, but is this a good idea? I do not know

**Comment by alexmurray** [comment]
Perhaps posframe could act as a minor mode for the buffers in which it is active - then just have a posframe-mode-hook which is called that users can use to run custom code within the frame / buffer?

**Comment by tumashu** [comment]
maybe we just need :func ,  i do not like :set keywords,   for its work can use :func

**Comment by noctuid** [comment]
The only issue with one minor mode for all posframe buffers is that I may want different setup depending on whether posframe is used for ivy vs. company. Maybe the hook could be run with an argument corresponding to the package using posframe. That or multiple minor modes.

**Comment by noctuid** [comment]
I don't think it makes sense to bind keys in a child frame buffer, does it? If not, a minor mode isn't necessary, just the hook.

**Comment by tumashu** [comment]
posframe only show,  it can not handle key setting

**Comment by tumashu** [comment]
posframe-mode-hook seem to be not a good idea .

**Comment by tumashu** [comment]
what about a :hook keyword?

**Comment by noctuid** [comment]
I don't think it matters too much how it's implemented as long as it's possible to customize per-package (i.e. Different settings for ivy vs company vs flycheck). A `:hook` keyword seems fine.

**Comment by tumashu** [comment]
Add :initialize, please test

**Comment by noctuid** [comment]
Looks fine. Thank you; I will test when I get the chance. I think it might be better to name that variable `... initialized-p` for clarity.

**Comment by tumashu** [comment]
good idea

**Comment by noctuid** [comment]
Since the user isn't generally using `posframe-show` directly, it would probably make sense to add a customizable variable in packages like ivy-posframe and then add something like `:hook ivy-posframe-buffer-setup-function` in their `posframe-show` call.

Also, I think it would be nice if there was a `posframe-buffer-setup-hook` because there is some global setup I want to do for every posframe buffer regardless of whether company or ivy or whatever is using it. You could just do this and not create a minor mode:

```elisp
(defcustom posframe-buffer-setup-hook nil
  "Hook run in the posframe buffer when it is first initialized."
  :type 'hook)
;; ...
;; in `posframe--create-posframe'
(run-hooks 'posframe-buffer-setup-hook)
```

**Comment by tumashu** [comment]
Try posframe-default-initialize-function

**Comment by noctuid** [comment]
What I had in mind is something that would always be called, not just as the default (e.g. so that I can have core setup in one place instead of duplicating it in every `:initialize` function).

**Comment by tumashu** [comment]
if :initialize is nil, this funciton will be called

**Comment by noctuid** [comment]
I want a function that will be called even when :initialize is non-nil.

**Comment by tumashu** [comment]
i will not add this feature, it let the package which use posframe out of  control the behave of posframe

**Comment by noctuid** [comment]
The point is for use by a user for default setup. Why is it preferable for a package that uses posframe to overwrite user configuration? It seems personally reasonable to me for the user to be able to perform generic setup in any posframe buffer (e.g. to disable line numbers in all posframe buffers by default).

**Comment by noctuid** [comment]
Sure, but the fact is that the user will ultimately end up interacting with this package. That's why it makes sense to have defcustoms in this package like `posframe-inhibit-double-buffering`. What's the difference between my suggested setting and the existing defcustoms? Packages that use posframe can't control how the user uses `posframe-inhibit-double-buffering` currently. And unless you want `:initialize` to only be used in packages and not by users, it doesn't matter if the user can set an always-used default. I don't really understand what your concern is.

**Comment by tumashu** [comment]
I have add a new feature: posframe-arghandler,  user can use this custom to control posframe-show's all arguments, maybe useful.

```
Set fallback argument of posframe-show

user can set fallback values of posframe-show's arguments with the help of `posframe-arghandler'. the below example set fallback border-width to 10 and fallback background color to green.

(setq posframe-arghandler #'my-posframe-arghandler)
(defun my-posframe-arghandler (posframe-buffer arg-name value)
  (let ((info '(:internal-border-width 10 :background-color "green")))
    (or (plist-get info arg-name) value)))

```
