### ISSUE TITLE
More builtin poshandlers

### ISSUE THREAD

**Issue by noctuid** [tumashu/posframe#15]
I think that `posframe-poshandler-frame-top-center` should be provided by default. To me this is by far the most useful position (e.g. it's the position that most other editors use by default for `C-p`).

Honestly, I think it might be better to just provide a helper to construct poshandlers. The parameter list might look something like this:

```
posframe-generate-poshandler (x y &key align-to x-offest y-offset) ...
;; x: number, 'left, 'center, or 'right
;; y: number, 'top, 'center, or 'bottom
;; align-to: 'window or 'frame
;; x and y offsets: number offset (e.g. useful if I want to have the frame a
;; little below the top of the window)
```

**Comment by tumashu** [comment]
```
posframe-poshandler-frame-top-center
```
Seem to be a good idea.

```
posframe-generate-poshandler
```
Maybe this is a good idea, but it seem to hard to code for the macro reason :-)

**Comment by noctuid** [comment]
> Maybe this is a good idea, but it seem to hard to code for the macro reason :-)

It could also be written as a function that returns a closure, but I think it would be better written as a macro. I can make a PR or at least post an example if you're interested.

**Comment by tumashu** [comment]
posframe-poshandler-frame-top-center has added
