### ISSUE TITLE
posframe can't show propertized string correctly

### ISSUE THREAD

**Issue by stardiviner** [tumashu/posframe#20]
Here is the demo code:

```elisp
(posframe-show " *result*"
                   :string (propertize ....) ; FIXME: did not auto wrap and fill.
                   :position (point)
                   )
```

**Comment by tumashu** [comment]
I do not understand this problem, please add a *workable* demo :-)

**Comment by stardiviner** [comment]
Here is my code which use `popup` function `popup-tip` which shows propertized text correctly like in this screenshot:

```
(defun edebug-inline-result-show ()
  "Show `edebug-previous-result' with specific popup backend."
  (interactive)
  (if (fboundp 'posframe-show)
      (posframe-show "*edebug-result*"
                     :string edebug-previous-result)
    (popup-tip edebug-previous-result
               :truncate t :height 20 :width 45 :nostrip t :margin 1 :nowait nil)))

(advice-add 'edebug-previous-result :override #'edebug-inline-result-show)
```

![image](https://user-images.githubusercontent.com/378699/53612052-af9b2d00-3c0b-11e9-991c-2c4d1a79d5da.png)

And if I use `posframe-show` When the properized text is long, it does not text auto fill, wrap long line text etc.

Here is the screenshot with `posframe-show`:

![image](https://user-images.githubusercontent.com/378699/53612680-626c8a80-3c0e-11e9-936f-3a9dceb62e6a.png)

**Comment by stardiviner** [comment]
Here is a simple pakcage try to do this using many different popup backends. https://github.com/stardiviner/edebug-inline-result

**Comment by stardiviner** [comment]
Also I don't know how to auto close the `posframe-show` child-frame after exited the Edebug session.

**Comment by tumashu** [comment]
我还是没看懂你说的情况，你的意思是，当posframe宽度固定时，内容不自动换行么？

**Comment by stardiviner** [comment]
是的，多出来的行内容都不见了。我看了 `posframe-show` 的参数，默认没有 auto-wrap
之类的。不知道怎么让它自动换行。

**Comment by tumashu** [comment]
对于 posframe， 你说默认设置为自动换行好呢，还是截断好？ 这两种情况分别有什么用途？

**Comment by stardiviner** [comment]
你说的截断是指 `truncate-lines` ？这个肯定不行，因为截断的话，文字不就不显示了么？posframe的本意是显示内容啊。所以我觉得还是 自动换行吧。

**Comment by tumashu** [comment]
默认设置为自动换行了

**Comment by tumashu** [comment]
```
Also I don't know how to auto close the posframe-show child-frame after exited the Edebug session.
```
在合适的时机调用 posframe-hide 就OK了
