### ISSUE TITLE
support scrolling (and other keyboard interaction) in posframe

### ISSUE THREAD

**Issue by junyi-hou** [tumashu/posframe#26]
As for now, one cannot interact with posframe with keystrokes. For example, I cannot scroll down (using keyboard) to see long content.

The workaround I use right now is to use `with-selected-frame` to define commands that run inside the posframe. Bind these posframe-specific commands in a separate keymaps. At the end of the `posframe-show` call `set-transient-map` to apply the bindings when the posframe appears.

I was wondering if there is any plan for posframe to provide this functionality in the future?

**Comment by tumashu** [comment]
Maybe , is this feature a good idea? i do not know at the moment

**Comment by tumashu** [comment]
we should know, posframe can not get focus when it work.

**Comment by junyi-hou** [comment]
I agree that letting posframe to get focus may cause all sorts of problem. But I was just wondering something like
`(with-selected-frame posframe--frame
   (scroll-up))`
would scroll posframe frame without having to directly focus on it. In this way, I can scroll up/down the posframe frame with my keyboard.

Let me know whether this makes sense to you. Thanks!

**Comment by tumashu** [comment]
we can try it

**Comment by junyi-hou** [comment]
I have put together a working prototype. I have basically defined a bunch new commands using the aforementioned snippet, bind them to a new keymap. Call `set-transient-map` at the end of the `posframe-show` function to activate the keymap, and allow it to deactivate this keymap when `posframe-hide` is called. The gif below shows the effect.

![Peek 2019-05-14 09-17](https://user-images.githubusercontent.com/40352771/57715102-c78b2600-762a-11e9-819c-fa67b217ef1f.gif)

If all of these make sense I can do a bit more tests and open a pull request.

Thanks!

**Comment by tumashu** [comment]
by the way, posframe is a gnu elpa package, do you assign FSF paper?

**Comment by junyi-hou** [comment]
no, I have not. And the implementation borrows some ideas from `lsp-ui`, would that still be OK?

**Comment by tumashu** [comment]
I think it it not OK :-(

**Comment by junyi-hou** [comment]
fair enough :(, what do you suggest I do? Should I just closed the issue and maybe upload the snippet in a separate repo?

**Comment by tumashu** [comment]
just update the snippet to here

**Comment by deadtrickster** [comment]
@junyi-hou please look here: https://github.com/tumashu/ivy-posframe/issues/16

will your code help with this?

**Comment by junyi-hou** [comment]
sorry I am busy recently. Should be able to work on this during the weekend.

@deadtrickster I think this is a separate problem, what I try to do here is to pass commends _without_ selecting the posframe. Your problem is that you are selecting the posframe.

**Comment by deadtrickster** [comment]
hmm, yea I should've split the issue in two in fact. The second problem is with a long lines - sometimes posframe does horizontal scrolling to the right (in my case it happens when counsel produces long lines). So I just stumbled on this issue and mentions scrolling. Thought might be a good chance to find the help.

**Comment by deadtrickster** [comment]
Oh and what especially interesting here: you can somehow control the scrolling. While  for me if this horizontal fuck up happens I have to kill respective posframe buffer and let it recreate.

**Comment by junyi-hou** [comment]
Please find attached the gist snippet for interactive posframe. Any suggestions are welcome!

https://gist.github.com/junyi-hou/ecd82e27aa1a436961974acedf4dbcf8

**Comment by tumashu** [comment]
i can not open this link

**Comment by junyi-hou** [comment]
see below

```
;;; posframe-control.el -- supporting keyboard control for posframe -*- lexical-binding: t; -*-

;; Package-requires: ((emacs "26") (posframe "0.3.0") (dash "2.16.0"))

;;; Commentary:

;; This snippet provides keyboard interaction support for posframe
;; (https://github.com/tumashu/posframe). This is achieved by 1.) assigning a
;; name to the posframe-frame via specifying `override-parameters'; 2.) defining
;; command using `with-selected-frame' to operate on the posframe.
;;
;; In order to overshadow current keymapings, I using `set-transient-map' to
;; temporarily activate keymap to control posframe. This keymap is automatically
;; deactivated when `posframe-hide' is called.


;; usage:

;; define posframe using `posframe-control-show' instead of `posframe-show'.
;; Customize `posframe-control-keymap' to suit your need. For any additional
;; command, define them using `posframe-control--define-command'

;; example:
;;
;; define new command:
;; (defun posframe-control-scroll-up ()
;;   (interactive)
;;   (posframe-control--define-command 'score-up))
;;
;; customize keymap
;; (define-key posframe-control-keymap (kbd "C-v") ;posframe-control-scroll-up)
;;
;; call posframe
;; (posframe-control-show
;;   "foo-buffer"
;;   :string "this posframe can be controlled")

;;; Code:

(require 'posframe)
(require 'dash)

(defgroup posframe-control nil
  "Group for posframe-control"
  :group 'posframe
  :prefix "posframe-control-")

(defcustom posframe-control-keymap
  (let ((map (make-sparse-keymap)))
    (suppress-keymap map t)
    (define-key map (kbd "q") 'posframe-control-hide)
    (define-key map (kbd "<escape>") 'posframe-control-hide)
    (define-key map (kbd "C-d") 'posframe-control-scroll-down)
    (define-key map (kbd "C-u") 'posframe-control-scroll-up)
    (define-key map (kbd "J") 'posframe-control-scroll-down)
    (define-key map (kbd "K") 'posframe-control-scroll-up)
    map)
  "Keymap for controlling posframes.  The default key for scroll up is `M-v' (`C-u' if `posframe-control-use-evil' is set to t), and the key for scroll down is `C-v' (`M-v' if `posframe-control-use-evil' is set to t).  Press `q' or `<escape>' to hide the current posframe."
  :type 'keymap
  :group 'posframe-control)

(defvar-local posframe-control--deactivate-fn nil)
(defvar-local posframe-control--frame nil)
(defvar-local posframe-control--buffer nil)


(defun posframe-control--define-command (command &rest arg)
  "Run COMMAND with ARG in `posframe-control--frame'."
  (if posframe-control--frame
      (with-selected-frame posframe-control--frame
        (apply command arg))
    (error "No posframe-control frame found")))

(defun posframe-control-scroll-down ()
  "Scroll half page down."
  (interactive)
  (posframe-control--define-command
   'scroll-up
   (max 1 (/ (1- (window-height (selected-window))) 2))))

(defun posframe-control-scroll-up ()
  "Scroll half page up."
  (interactive)
  (posframe-control--define-command
   'scroll-down
   (max 1 (/ (1- (window-height (selected-window))) 2))))

(defun posframe-control-hide ()
  "Hide posframe."
  (interactive)
  (setq-local posframe-control--frame nil)
  (posframe-hide posframe-control--buffer)
  (ignore-errors
   (-when-let (fn posframe-control--deactivate-fn)
    (setq posframe-control--deactivate-fn nil)
    (funcall fn))))

(defun posframe-control--get-posframe ()
  "Return the frame object for the posframe."
  (-some (lambda (frame)
           (when (equal "posframe-control--frame" (frame-parameter frame 'name))
             frame))
         (frame-list)))

(defun posframe-control-show (posframe-buffer &rest args)
  "Wrapper around `posframe-show'. Create a child-frame that is controlable."
  (posframe-show
   posframe-buffer
   :string (plist-get args :string)
   :position (plist-get args :position)
   :poshandler (plist-get args :poshandler)
   :width (plist-get args :width)
   :height (plist-get args :height)
   :min-width (plist-get args :min-width)
   :min-height (plist-get args :min-height)
   :x-pixel-offset (plist-get args :x-pixel-offset)
   :y-pixel-offset (plist-get args :y-pixel-offset)
   :left-fringe (plist-get args :left-fringe)
   :right-fringe (plist-get args :right-fringe)
   :internal-border-width (plist-get args :internal-border-width)
   :internal-border-color (plist-get args :internal-border-color)
   :font (plist-get args :font)
   :foreground-color (plist-get args :foreground-color)
   :background-color (plist-get args :background-color)
   :respect-header-line (plist-get args :respect-header-line)
   :respect-mode-line (plist-get args :respect-mode-line)
   :face-remap (plist-get args :face-remap)
   :initialize (plist-get args :initialize)
   :no-properties (plist-get args :no-properties)
   :keep-ratio (plist-get args :keep-ratio)
   :timeout (plist-get args :timeout)
   :refresh (plist-get args :refresh)
   :override-parameters '((name . "posframe-control--frame")
                          (no-accept-focus . nil)))

  (setq-local posframe-control--buffer posframe-buffer)
  (setq-local posframe-control--frame (posframe-control--get-posframe))
  (setq-local posframe-control--deactivate-fn (set-transient-map
                                               posframe-control-keymap
                                               t
                                               'posframe-control-hide)))


(provide 'posframe-control)
;;; posframe-control.el ends here
```

**Comment by tumashu** [comment]
(no-accept-focus . nil)?   this seem to let posframe get focus,  what happen if you type other key when posframe-control enable?    insert key to poframe's buffer?

**Comment by junyi-hou** [comment]
1. posframe would never gain focus, therefore press any other key will not insert them into posframe. That is why we need to use `with-selected-frame` to issue commands in the first place.

2. by definition, `set-transient-map` makes sure that for any key that is not in the `posframe-control-keymap`, the posframe will hide and we return to the parent frame. In fact, if you don't define `mouse-1`, you can't even actively choose the childframe, let alone controlling for it.

3. I tried setting `no-accept-focus` to t, but then it cannot be selected by `with-selected-frame`. I would love to know workarounds if they exist.

**Comment by junyi-hou** [comment]
I should apologize that I did not articulate the idea.

The way `posframe-control` works is 1. make a posframe with a specific name, 2. use `set-transient-map` to overshadow current keymap, 3. for any keypress outside of `posframe-control-map`, hide the posframe and execute whatever command bind to that key in the parent frame, 4. for any keypres inside of `posframe-control-map`, execute command using `with-selected-frame posframe-control-frame` indrectly execute command in the posframe.

I hope this clarifies the idea.

**Comment by tumashu** [comment]
when posframe-show called, the focus is in current buffer, and not in posframe's buffer, how to active posframe-control's keybinding?

**Comment by junyi-hou** [comment]
Posframe is a frame, so we can call command from other frames (in this case, the parent frame and the current buffer) using with-selected-frame

**Comment by tumashu** [comment]
Is posframe-control is your need?
```
(cl-defun posframe-control (posframe-buffer
                            &key
                            command
                            &allow-other-keys)
  (with-current-buffer posframe-buffer
    (when (framep posframe--frame)
      (with-selected-frame posframe--frame
        (when (functionp command)
          (funcall command))))))

(posframe-show
 "foo-buffer"
 :height 5
 :string "this posframe can be controlled
1
2
3
4
5
6
7
7
8
9
10
11
12")

(posframe-control "foo-buffer" :command 'scroll-up)


```

**Comment by junyi-hou** [comment]
Thanks! This is definitely better than mine. Do you also recommend bind various commands to a transient-map and activate it when the posframe is visible so I don’t have to bind these posframe control commands to different keys?

**Comment by tumashu** [comment]
bind various commands to a transient-map and activate it, this should to do in package which call posframe

**Comment by tumashu** [comment]
use company as example: when posframe show candidate menu, a minor mode is active, custom its keymap to add posframe control key

**Comment by tumashu** [comment]
https://github.com/tumashu/posframe/commit/e4f171f2267efa29822c85318bcd2bf014137e58
