### ISSUE TITLE
Rendering of a posframe moves pointer to first line of frame

### ISSUE THREAD

**Issue by billywade** [tumashu/posframe#27]
Any time a new posframe is created, regardless of where it is on the screen, my pointer goes to the space just to the left of the first line in my existing buffer. 

![posframe](https://user-images.githubusercontent.com/28458492/57931147-71fa8780-787d-11e9-8537-acfbeadeecc4.gif)

Let me know what you need from me. Thanks!

**Comment by articuluxe** [comment]
What is your value for ‘mouse-avoidance-mode?

**Comment by billywade** [comment]
I haven't customized it. In fact, I hadn't heard of it until you pointed it out to me. Looking at the definition, though, it looks like it doesn't have a built-in default, so having it left uncustomized shouldn't produce behaviour like this.

**Comment by terlar** [comment]
Isn't this the configuration variable `posframe-mouse-banish`, I put it as `(setq posframe-mouse-banish nil)` to avoid the mouse being moved.

**Comment by billywade** [comment]
@terlar that's the solution. Is there any way that could get `posframe-mouse-banish` added into the README @tumashu?

**Comment by terlar** [comment]
Agreed, I just happened to know this because I follow this repo and saw the discussion in: https://github.com/tumashu/posframe/issues/19

**Comment by billywade** [comment]
Just submitted pull #28 as a fix.

**Comment by billywade** [comment]
My problem is solved and I got my documentation in, closing

**Comment by defaultxr** [comment]
Alternate solution for this issue, which alleviates the need for the `posframe-mouse-banish` hack:

```elisp
(defvar posframe--previous-frame nil)

(defun posframe--redirect-posframe-focus ()
  "Select a different frame if the current frame is a posframe."
  (interactive)
  (if (eq (selected-frame) posframe--frame)
      (when posframe--previous-frame
        (redirect-frame-focus posframe--frame posframe--previous-frame))
    (progn
      (setf posframe--previous-frame (selected-frame))
      (when posframe--frame
        (redirect-frame-focus posframe--frame posframe--previous-frame)))))

(add-hook 'focus-in-hook 'posframe--redirect-posframe-focus)
```

This uses Emacs' built-in `redirect-frame-focus` command to re-route focus for a frame to a different frame.

Anytime the posframe is selected, we immediately redirect focus back to whatever the previous frame was.

Anytime a non-posframe frame is selected, we record it so we know which to redirect to. Additionally, if a posframe exists at that moment, we make sure its focus is redirected from the posframe to it.

Might submit this as a PR if it doesn't seem to result in other issues.

**Comment by tumashu** [comment]
@defaultxr this approach seem to better
