### ISSUE TITLE
Possible to add more advanced usage examples to README?

### ISSUE THREAD

**Issue by dangom** [tumashu/posframe#33]
I've been trying to modify `org-insert-structure-template`, currently bound to `C-c C-,` in recent Org versions, to use a posframe instead of using another window with `org-switch-to-buffer-other-window`.
The function I wanted to adapt, specifically, is `org-mks`, defined in `org-macs.el`.
Despite attempts to get posframe working, I couldn't get it to show up, perhaps because of weird interactions with `save-window-excursion` and `with-current-buffer`, etc.

I was wondering whether it'd be possible to show more advanced examples in the README.md to help new users figure out how to use posframe as a drop-in replacement for creating new windows. 
Alternatively, is there any other documentation or tutorials out there?

Thanks for the project

**Comment by conao3** [comment]
I am a maintainer of `ivy-posframe`.
If you use `posframe` simply, you only need to read the code and read the readme, or you can get the application by reading a package that uses `posframe`.

- [posframe](https://github.com/tumashu/posframe) by tumashu
  - [ivy-posframe](https://github.com/tumashu/ivy-posframe) by tumashu
  - [helm-posframe](https://github.com/tumashu/helm-posframe) by tumashu
  - [company-posframe](https://github.com/tumashu/company-posframe) by tumashu
  - [which-key-posframe](https://github.com/yanghaoxie/which-key-posframe) by yanghaoxie
  - [ddskk-posframe](https://github.com/conao3/ddskk-posframe.el) by conao3

(cited from ddskk-posframe readme)

I was surprised that there was a plan to use posframe with org. I support the plan.
What kind of example do you feel that is not enough?
`posframe` with `weird interactions with save-window-excursion and with-current-buffer, etc.`?

**Comment by dangom** [comment]
Not sure, perhaps I just know too little about child frames, and it's not an issue with posframe, just my own ignorance. Thanks a lot for responding so quickly and for all examples, by the way.

I was wondering when can we use posframe as a replacement for other window or frame generating functions. For Org mode, my plan was to first substitute `org-insert-structure-template`, and then later maybe the export menu.

Here's the original org function I wanted to modify, with some personal comments (marked with !!!):
```
(defun org-mks (table title &optional prompt specials)
  "Select a member of an alist with multiple keys.

TABLE is the alist which should contain entries where the car is a string.
There should be two types of entries.

1. prefix descriptions like (\"a\" \"Description\")
   This indicates that `a' is a prefix key for multi-letter selection, and
   that there are entries following with keys like \"ab\", \"ax\"...

2. Select-able members must have more than two elements, with the first
   being the string of keys that lead to selecting it, and the second a
   short description string of the item.

The command will then make a temporary buffer listing all entries
that can be selected with a single key, and all the single key
prefixes.  When you press the key for a single-letter entry, it is selected.
When you press a prefix key, the commands (and maybe further prefixes)
under this key will be shown and offered for selection.

TITLE will be placed over the selection in the temporary buffer,
PROMPT will be used when prompting for a key.  SPECIALS is an
alist with (\"key\" \"description\") entries.  When one of these
is selected, only the bare key is returned."
  (save-window-excursion
    (let ((inhibit-quit t)
          ;;; !!! Here we don't want to use a window, we want a posframe.
	  (buffer (org-switch-to-buffer-other-window "*Org Select*"))
	  (prompt (or prompt "Select: "))
	  current)
      (unwind-protect
	  (catch 'exit
	    (while t
	      (erase-buffer)
	      (insert title "\n\n")
	      (let ((des-keys nil)
		    (allowed-keys '("\C-g"))
		    (tab-alternatives '("\s" "\t" "\r"))
		    (cursor-type nil))
		;; Populate allowed keys and descriptions keys
		;; available with CURRENT selector.
		(let ((re (format "\\`%s\\(.\\)\\'"
				  (if current (regexp-quote current) "")))
		      (prefix (if current (concat current " ") "")))
		  (dolist (entry table)
		    (pcase entry
		      ;; Description.
		      (`(,(and key (pred (string-match re))) ,desc)
		       (let ((k (match-string 1 key)))
			 (push k des-keys)
			 ;; Keys ending in tab, space or RET are equivalent.
			 (if (member k tab-alternatives)
			     (push "\t" allowed-keys)
			   (push k allowed-keys))
			 (insert prefix "[" k "]" "..." "  " desc "..." "\n")))
		      ;; Usable entry.
		      (`(,(and key (pred (string-match re))) ,desc . ,_)
		       (let ((k (match-string 1 key)))
			 (insert prefix "[" k "]" "     " desc "\n")
			 (push k allowed-keys)))
		      (_ nil))))
		;; Insert special entries, if any.
		(when specials
		  (insert "----------------------------------------------------\
---------------------------\n")
		  (pcase-dolist (`(,key ,description) specials)
		    (insert (format "[%s]     %s\n" key description))
		    (push key allowed-keys)))
		;; Display UI and let user select an entry or
		;; a sub-level prefix.
		(goto-char (point-min))
                ;;; !!! Perhaps simply remove this code, since we are not using a window?
		(unless (pos-visible-in-window-p (point-max))
		  (org-fit-window-to-buffer))
		(let ((pressed (org--mks-read-key allowed-keys prompt)))
		  (setq current (concat current pressed))
		  (cond
		   ((equal pressed "\C-g") (user-error "Abort"))
		   ;; Selection is a prefix: open a new menu.
		   ((member pressed des-keys))
		   ;; Selection matches an association: return it.
		   ((let ((entry (assoc current table)))
		      (and entry (throw 'exit entry))))
		   ;; Selection matches a special entry: return the
		   ;; selection prefix.
		   ((assoc current specials) (throw 'exit current))
		   (t (error "No entry available")))))))
        ;;; !!! Here we also have to exit the posframe
	(when buffer (kill-buffer buffer))))))
```

I don't see how to simply replace calls to functions that would use windows to calls that use posframe.

**Comment by conao3** [comment]
OK. I'll see it later.

**Comment by dzop** [comment]
It would be cool to have some kind of package to use `posframe` instead of pop-up windows, below is some code that I believe can be used as a starting point.

I believe the strategy should be to call all of the `org` functions normally, but inside the `posframe`, and use `cl-letf` or hooks to strategically resize the `posframe` whenever it needs to be, i.e. whenever `org` updates the selection buffer to display a different sub-menu. This way we don't have to modify any of the `org` functions at all.

```emacs-lisp
(with-temp-buffer
  ;; Need to link a different buffer other than "*Org Select*" to the posframe
  ;; since `org-mks' deletes the buffer before it returns.
  (let ((posframe-buffer (current-buffer)))
    (cl-letf* ((orig (symbol-function #'org--mks-read-key))
               ((symbol-function #'org--mks-read-key)
                (lambda (&rest args)
                  ;; Fit the posframe to its contents when reading a key since
                  ;; `org-mks' modifies the buffer contents before asking the
                  ;; user for a key.
                  (fit-frame-to-buffer)
                  (apply orig args))))
      (with-current-buffer (get-buffer-create "*Org Select*")
        (posframe-show
         posframe-buffer
         :string ""
         :background-color "#dddddd"
         :poshandler 'posframe-poshandler-frame-top-center)
        ;; Suppress the window splitting of the
        ;; `org-switch-to-buffer-other-window' call in `org-mks'.
        (let ((display-buffer-overriding-action
               '(display-buffer-same-window)))
          ;; Call `org-mks' in the posframe
          (posframe-funcall
           posframe-buffer 'org-mks
           '(("r" "Round fruits")
             ("ra" "Apples" 1))
           "Fruits")
          (posframe-delete posframe-buffer))))))
```

**Comment by tumashu** [comment]
Added, https://github.com/tumashu/posframe/commit/dcc281c6e8787557d3181818b7035adb292ad338
