### ISSUE TITLE
Add options for space between border and text?

### ISSUE THREAD

**Issue by AmaiKinono** [tumashu/posframe#34]
See the discussion at https://github.com/hlissner/emacs-doom-themes/issues/296. Now the border is close to the text, and it would look better if there's some space. I can think of two ways to do this:

- Have a `internal-boarder-padding-space` parameter.
- Add outer border parameters, and use internal border for padding.

**Comment by tumashu** [comment]
can we change outer border color?

**Comment by tumashu** [comment]
you can use :override-parameters

OVERRIDE-PARAMETERS is very powful, *all* the frame parameters
used by posframe's frame can be overrided by it.

**Comment by AmaiKinono** [comment]
> can we change outer border color?

I don't quite understand. It's not an option of `posframe-show` now.

> you can use :override-parameters

I am using `ivy-posframe` and I did this:

``` emacs-lisp
(setq
 ivy-posframe-parameters '((border-width . 10)
                           (border-color . "gray20")))
```

Seems it doesn't have any effect. Could you tell me the right way to do this?

**Comment by tumashu** [comment]
override-parameters means override frame-parameters  used inside of posframe

**Comment by tumashu** [comment]
```
  (make-frame
                     `(,@override-parameters
                       ,(when foreground-color
                          (cons 'foreground-color foreground-color))
                       ,(when background-color
                          (cons 'background-color background-color))
                       ,(when font
                          (cons 'font font))
                       (parent-frame . ,(or parent-frame (window-frame)))
                       (keep-ratio ,keep-ratio)
                       (posframe-buffer . ,(cons (buffer-name posframe-buffer)
                                                 posframe-buffer))
                       (fullscreen . nil)
                       (no-accept-focus . t)
                       (min-width  . 0)
                       (min-height . 0)
                       (border-width . 0)
                       (internal-border-width . ,internal-border-width)
                       (vertical-scroll-bars . nil)
                       (horizontal-scroll-bars . nil)
                       (left-fringe . ,left-fringe)
                       (right-fringe . ,right-fringe)
                       (menu-bar-lines . 0)
                       (tool-bar-lines . 0)
                       (line-spacing . 0)
                       (unsplittable . t)
                       (no-other-frame . t)
                       (undecorated . t)
                       (visibility . nil)
                       (cursor-type . nil)
                       (minibuffer . nil)
                       (width . 1)
                       (height . 1)
                       (no-special-glyphs . t)
                       (inhibit-double-buffering . ,posframe-inhibit-double-buffering)
                       ;; Do not save child-frame when use desktop.el
(desktop-dont-save . t))))
```

**Comment by AmaiKinono** [comment]
Hi. I think I already know why it doesn't work. My config is right, but it's said in [the manual](https://www.gnu.org/software/emacs/manual/html_node/elisp/Frame-Layout.html) that:

> Usually, the outer border is shown only for special frames ... like tooltip frames (see Tooltips), child frames (see Child Frames)

> Outer borders are never shown on text terminal frames and on frames generated by GTK+ routines. On MS-Windows, the outer border is emulated with the help of a one pixel wide external border. Non-toolkit builds on X allow to change the color of the outer border by setting the border-color frame parameter

I am using a GTK build of Emacs on linux. I tried on windows and it works. So basically the outer border:

- doesn't show if you use a normal GTK build on linux.
- is emulated by a 1 pixel line on windows, despite of the parameter `border-width`
- maybe shows correctly on macOS.

So this is not a problem of `posframe` but Emacs itself.
