### ISSUE TITLE
internal-border-color is delayed

### ISSUE THREAD

**Issue by iwai** [tumashu/posframe#38]
border-color delayed, this problem occurred with GUI Emacs.
It will appear when you move the cursor or move the window. in addition to Carbon, it also occurred in the Mac port version.

EmacsVersion: GNU Emacs 26.2 (build 1, x86_64-apple-darwin18.5.0, Carbon Version 158 AppKit 1671.4)

Try this code.

```elisp
(defun sample-show ()
  (posframe-show "*emacs-mac buffer*"
                 :string "hello"
                 :width  100
                 :height 10
                 :timeout 5
                 :internal-border-width 5
                 :internal-border-color "#ff0000"
                 :foreground-color "#000000"
                 :background-color "#FFFFFF")
  )
(sample-show)
```

![screencast](https://user-images.githubusercontent.com/84846/62076001-93b2ba80-b281-11e9-8b15-c2c2cb355c24.gif)

**Comment by conao3** [comment]
Hi. I'm ivy-posframe maintainer and Emacs on Mac user so I'm interested in this issue.
Currently, posframe on Mac have few issue but I cannot reproduce your issue.

## Emacs-26.1 with emacs-mac-port patch
![Untitled6](https://user-images.githubusercontent.com/4703128/62077632-88618e00-b285-11e9-9ff5-9f362184ed2e.gif)

## Emacs-26.2 without any patch (in other words `NS build`)
![Untitled7](https://user-images.githubusercontent.com/4703128/62077713-c65eb200-b285-11e9-9485-53e270b56d35.gif)

---
The border issue is reported in many places and the issue still remains. I think the issue should be reported in Emacs-dev ML.
Ref: https://github.com/tumashu/posframe/issues/30

**Comment by conao3** [comment]
Because I think this issue is not related to posframe. just child-frame issue.

**Comment by iwai** [comment]
Thank you for your quick reply.
As you say, this problem seems to be the content to be reported by Emacs-dev, and this issue closes with this.

**Comment by apc** [comment]
Is this issue supposed to *not* arise with the Mac port build? I'm having the same issue as the OP with Mac port version of emacs  27. 

`(GNU Emacs 27.1 (build 1, x86_64-apple-darwin18.7.0, Carbon Version 158 AppKit 1671.6) of 2020-08-17)`

![image](https://user-images.githubusercontent.com/350504/94184854-876cc200-fe72-11ea-9779-0c8302275b2c.png)
