### ISSUE TITLE
posframe-delete doesn't kill the posframe buffer

### ISSUE THREAD

**Issue by mamapanda** [tumashu/posframe#39]
It seems that passing in a buffer name to `posframe-delete` doesn't actually kill the posframe buffer, despite what the readme suggests. I think it's because `buffer-live-p` (used in `posframe--kill-buffer`) expects a buffer object and not a string.

Environment: Emacs 26.2 on Manjaro Linux

Reproduction steps:
- Evaluate the following with `emacs -Q`:
```
(require 'package)
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/"))
(package-initialize)

(unless (package-installed-p 'posframe)
  (package-refresh-contents)
  (package-install 'posframe))

(require 'posframe)

;; the below is copied from the readme

(when (posframe-workable-p)
  (posframe-show " *my-posframe-buffer*"
                 :string "This is a test"
                 :position (point)))

(posframe-delete " *my-posframe-buffer*")
```
- Evaluate `(get-buffer " *my-posframe-buffer*")`. It returns non-nil.

**Comment by tumashu** [comment]
Fixed, thanks!
