### ISSUE TITLE
Can't close posframe after clicking out of it

### ISSUE THREAD

**Issue by ema2159** [tumashu/posframe#43]
If I for example use an ivy-posframe's command to pop up a posframe but I click outside of the posframe, it remains there and there's no way to close it besides closing Emacs.

**Comment by tumashu** [comment]
try posframe-delete-all

**Comment by ema2159** [comment]
That works, but good update would be to apply `posframe-delete-all` when the user clicks away of the posframe. Emacs shouldn't be used with the mouse at all but imagine this use case: I'm using Ivy-posframe to open a file, but I forgot the path of the file or the name so I go to look it up in another app (clicking with the mouse). When I come back now I click in Emacs, the posframe should either be focused again (which for some reason doesn't happen) or dissapear, but neither of those two things happen.

**Comment by tumashu** [comment]
posframe should not get focus, when use ivy-posframe, focus always in minibuffer
