### ISSUE TITLE
Posframe last element is not visible 

### ISSUE THREAD

**Issue by ema2159** [tumashu/posframe#44]
Original issue: https://github.com/tumashu/ivy-posframe/issues/68
If I use Ivy posframe to load a file and I go to the last element of the list, I'm unable to read it.
For example:
![image](https://user-images.githubusercontent.com/17773218/62568147-d52b0300-b849-11e9-8ce8-ffaa70767855.png)

**Comment by tumashu** [comment]
maybe this problem is for ivy-posframe instead of posframe, ivy-posframe add prompt after posframe-show

**Comment by ilohmar** [comment]
It may be simply cut off, I am investigating a similar effect due to a bug in Emacs' `fit-frame-to-buffer` right now.

Do you have `line-spacing` larger than 0 in that frame, by any chance?

**Comment by tumashu** [comment]
line-spacing?

**Comment by ilohmar** [comment]
Yes. Not sure what you are asking.

The emacs bug is 37563. I am not sure that they are related, this one just reminded me. 

On September 30, 2019 11:45:25 PM GMT+02:00, tumashu <notifications@github.com> wrote:
>line-spacing?
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/tumashu/posframe/issues/44#issuecomment-536766094

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
