### ISSUE TITLE
Posframe isn't working in the terminal

### ISSUE THREAD

**Issue by jessekelly881** [tumashu/posframe#46]
Issue: posframe does not work when emacs is running in the terminal. But, works fine when running in as GUI. 

I almost always use emacs in the terminal. Packages like company seem to be able to create child frames in the terminal. It would be nice if posframe could do this.

**Comment by tumashu** [comment]
can child-frame work in terminal emacs? really?

**Comment by jessekelly881** [comment]
Hmm. After some testing I can't seem to create child frames in the terminal. But, company seems to be creating something resembling child frames which it uses for completions. Here is a pic. 

![childframe](https://user-images.githubusercontent.com/22938931/65469534-5751a400-de57-11e9-98d2-ca5e994cffb8.jpg)

**Comment by jessekelly881** [comment]
Hmm. It seems to be using display-buffer instead of creating a child frame. I will see if I can get it working over the next few days and maybe send you a diff. It would be extremely useful (at least for me) to have posframe working in the terminal.

**Comment by tumashu** [comment]
maybe it is popup.el

**Comment by jessekelly881** [comment]
Ah possibly. It looks very similar to what I'm looking for. Thanks!
