### ISSUE TITLE
Frame not tall enough if line-spacing > 0

### ISSUE THREAD

**Issue by ilohmar** [tumashu/posframe#48]
When the default line-spacing is not 0, the posframe is not tall enough to fit the full height of the buffer.  The reason is that the line-spacing was ignored when calculating the pixel-exact height.  

For example, with a default char-height of 12, 6 lines to display yield a frame that's 72 pixels high, but if line-spacing is, say, 1, 6 full lines need 6 * (12+1) = 78 pixels, and the last line is cut off.

`posframe--set-frame-size` uses two different code paths to set the posframe's size.  The `fit-frame-to-buffer` call has been fixed on Emacs' master, see Emacs bug#37563 and commit e3f97d73653df725322d7f2392d36f858cce5a73.

BUT there is another path calling the C function `set-frame-size` directly, and that also ignores the line-spacing.  I think this call was introduced in posframe as an optimization to avoid the lenghty calculations on the lisp side.

I just confirmed on emacs-devel that `set-frame-size` behaves as it should:
https://lists.gnu.org/archive/html/emacs-devel/2019-10/msg00482.html

That means that posframe must not call `set-frame-size` directly, or it must calculate the pixel size itself and use the optional PIXELWISE argument.  To do this correctly, it will need to duplicate the work that `fit-frame-to-buffer` does, anyway.

So the fix is to simply replace calls to `posframe--set-frame-size` by `fit-frame-to-buffer` (same parameters), and the var `posframe--last-posframe-size` can be removed.

As for issue #44, there is no answer yet to know if it will be affected.

**Comment by tumashu** [comment]
maybe we can let posframe force set line space to 0?

**Comment by ilohmar** [comment]
Possible, but kind of intrusive, right? :)  I set line-spacing to 1 for a good reason: with my font choice it avoids looking too crowded and dense.

One of the main reasons for me to use company-posframe is that it makes for a cleaner, nicer look.  So naturally, I would like to keep the nice look of my font (vs line height) in posframe in particular.

Was the reason for `posframe--set-frame-size` a speedup, ie, less lag?  In that case, maybe we could check for line-spacing in this function, and note in the docs that a value other than 0 means that we must use more complex code, and hence will be somewhat slower.  If you agree, I'd be happy to do a PR for that.

**Comment by tumashu** [comment]
```
(defun posframe--set-frame-size (posframe height min-height width min-width)
  "Set POSFRAME's size.
It will set the size by the POSFRAME's HEIGHT, MIN-HEIGHT
WIDTH and MIN-WIDTH."
  (if (and width height)
      (unless (equal posframe--last-posframe-size
                     (cons width height))
        (set-frame-size posframe width height)
        (setq-local posframe--last-posframe-size
                    (cons width height)))
    (fit-frame-to-buffer
posframe height min-height width min-width)))
```
maybe we can add (if line-space > 0 condition,

**Comment by tumashu** [comment]
https://github.com/tumashu/posframe/blob/bb1393383d512d7358549c99f95b45e7d56d7d2c/posframe.el#L609

does it work when replace this line with fit-frame-to-buffer?

**Comment by ilohmar** [comment]
Yes it does.

Is caching the size really helpful?  I have no idea.  In any case, that would also fix the bug.

**Comment by ilohmar** [comment]
Thanks, works fine!
