### ISSUE TITLE
position of the frame not taken into account in os x

### ISSUE THREAD

**Issue by brabalan** [tumashu/posframe#5]
It seems that the position of the posframe does not take into account the position of the frame in OS X:
![screen shot 2018-03-09 at 14 00 51](https://user-images.githubusercontent.com/1021637/37208731-582e8704-239a-11e8-9cce-94a6cd2d38e5.png)

If the frame is on the left of the screen, it works better:
![screen shot 2018-03-09 at 14 03 57](https://user-images.githubusercontent.com/1021637/37208782-7ab2c114-239a-11e8-9fd5-4c87a776356a.png)

**Comment by tumashu** [comment]
emacs> 29.0.91 ?

**Comment by brabalan** [comment]
I'm not from the future ;)

GNU Emacs 26.0.91 (build 1, x86_64-apple-darwin17.4.0, Carbon Version 158 AppKit 1561.2) of 2018-03-09

It's this one (compiled from the git, work branch): https://bitbucket.org/mituharu/emacs-mac

**Comment by tumashu** [comment]
Sorry, I have no mac, so hard to debug this problem.

**Comment by seagle0128** [comment]
I think it's related to the dual-monitors?

**Comment by brabalan** [comment]
I just tried with no external monitor and I still have the issue.

**Comment by tumashu** [comment]
what window-manager?

**Comment by brabalan** [comment]
@tumashu It's still OS X, so it's the default WM.

**Comment by tumashu** [comment]
...

**Comment by mituharu** [comment]
The version OP referring to does not support the `parent-frame` frame parameter yet.
I wrote at http://lists.gnu.org/archive/html/emacs-devel/2017-10/msg00418.html as follows:

> The bare development branch of the Mac port is now based on Emacs
26.0.90 pretest:

>   https://bitbucket.org/mituharu/emacs-mac.git

> The branch name is "work".  It should be considered as experimental/hackers-only.

> At the moment, the new frame parameters `parent-frame` and `undecorated` are not supported yet.  I have some premature code internally, but not included in the repository above.

The code for these frame parameters is almost ready on my side.  I'll install it within a week.

**Comment by brabalan** [comment]
@mituharu Great news, thanks. I switched to the 26 branch because it's required by this package (and I can gladly report everything works great, with this tiny exception).

Will it be possible to disable the title bar for such frames?

**Comment by mituharu** [comment]
With the current implementation on my side, child frames have no title bar regardless of the value of the `undecorated` frame parameter just like on X11.  The major difference from X11 is a child frame is not clipped by its parent.

**Comment by brabalan** [comment]
This is perfect, thanks!

**Comment by brabalan** [comment]
I confirm that this now works great.

**Comment by tumashu** [comment]
Wow, good job....
