### ISSUE TITLE
Dynamically resize posframe [DE Gnome]

### ISSUE THREAD

**Issue by clemera** [tumashu/posframe#51]
Is it possible to resize the posframe when the buffer contents change? I tried `(fit-frame-to-buffer posframe--frame)` with no success.

**Comment by tumashu** [comment]
try posframe-show's refresh argument

**Comment by tumashu** [comment]
I have added  posframe-refresh, you can try:
```
(defun posframe-refresh (buffer-or-name)
  "Refresh posframe pertaining to BUFFER-OR-NAME.

For example:

   (defvar buf \" *test*\")
   (posframe-show buf)

   (with-current-buffer buf
     (erase-buffer)
     (insert \"ffffffffffffff\")
     (posframe-refresh buf))

User can use posframe-show's :refresh argument,
to do similar job:

   (defvar buf \" *test*\")
   (posframe-show buf :refresh 0.25)

   (with-current-buffer buf
     (erase-buffer)
     (insert \"ffffffffffffff\"))"
  (dolist (frame (frame-list))
    (let ((buffer-info (frame-parameter frame 'posframe-buffer)))
      (when (or (equal buffer-or-name (car buffer-info))
                (equal buffer-or-name (cdr buffer-info)))
        (with-current-buffer buffer-or-name
          (apply #'fit-frame-to-buffer
                 frame posframe--last-posframe-size))))))

```

**Comment by clemera** [comment]
Very nice! Thank you!

**Comment by clemera** [comment]
For your info: I tried with `emacs -Q` and this does not work on Emacs 26.3, the posframe does not update its size. There is only the first character showing when changing the buffers content.

**Comment by tumashu** [comment]
do you update to newest posframe?

**Comment by tumashu** [comment]
https://github.com/tumashu/posframe/commit/d5048672606535e6632131979817e4d7591f8b08

**Comment by conao3** [comment]
It's working for me.

Do you use posframe on GNOME? posframe on GNOME can't resize the frame size. It's an upstream's limitation.

**Comment by tumashu** [comment]
I do not use gnome, just use xfce, child-frame need some features of window-manager.

At 2019-12-12 08:47:39, "Naoya Yamashita" <notifications@github.com> wrote:


It's working for me.

Do you use posframe on GNOME? posframe on GNOME can't resize the frame size. It's an upstream's limitation.

**Comment by clemera** [comment]
Yes I use the latest version on Gnome :( Time to switch my DE I guess ;) Thanks for the help!

**Comment by clemera** [comment]
Couldn't find this info on Gnome limitation anywhere, maybe reopen this issue so others using Gnome can easily find it?

**Comment by tumashu** [comment]
good idea

**Comment by clemera** [comment]
[Here](https://gitlab.gnome.org/GNOME/mutter/issues/840) one can find the relevant issue for Gnome
