### ISSUE TITLE
autoload posframe-workable

### ISSUE THREAD

**Issue by seagle0128** [tumashu/posframe#52]
I think it's better autoload `posframe-workable`, otherwise have to `(require 'posframe` to check if `posframe` is available. That doesn't make sense. BTW, the example doesn't work if not `require` it.

https://github.com/tumashu/posframe/blob/5b2e3fcefce3a0c990c164dbf65009844e0cca74/posframe.el#L200

**Comment by tumashu** [comment]
Fixed
