### ISSUE TITLE
Position for font-height invalid

### ISSUE THREAD

**Issue by algoterranean** [tumashu/posframe#53]
## Problem:
Switching window configs while a posframe is open can result in `posframe-show` looking to set `font-height` using a position that is no longer valid (if the buffer sizes of these two windows are different).

## One way replicate:
1. Enable `eyebrowse`.
2. Switch to window config number 1.
3. In this window config, open up a file with, say, 500 characters.
4. Switch to window config number 2. 
5. In this window config, open up a file with less than 500 characters.
6. Switch to window config number 1.
7. Move point to end of buffer.
8. _While posframe is open_ (e.g. a hydra-posframe that allows for eyebrowse switching), switch to window config 2.

## Result:
`posframe-show` will be using the `point` value from the window of workspace 1 (`position` = 500), but then attempt to set `font-height` using the window of workspace 2 at this same position, which is invalid (since this buffer is smaller than 500).

## Error message will look like :
```
Debugger entered--Lisp error: (args-out-of-range 52756 1 40057)
  font-at(52756)
  (progn (font-at (if (and (= position (point-max))) (- position 1) position)))
  (if (and (integerp position) (not (= position 1))) (progn (font-at (if (and (= position (point-max))) (- position 1) position))))
  (let* ((font (if (and (integerp position) (not (= position 1))) (progn (font-at (if (and ...) (- position 1) position))))) (height (if (integerp position) (progn (if (or (= position 1) (not ...)) (default-line-height) (aref (font-info font) 3)))))) (setq posframe--last-font-height-info (cons position height)) height)
  (if (eq position (car posframe--last-font-height-info)) (cdr posframe--last-font-height-info) (let* ((font (if (and (integerp position) (not (= position 1))) (progn (font-at (if ... ... position))))) (height (if (integerp position) (progn (if (or ... ...) (default-line-height) (aref ... 3)))))) (setq posframe--last-font-height-info (cons position height)) height))
  posframe--get-font-height(52756)
```

## Possible solution:
In `posframe-show`, change `font-height` so that it is set via:
```
(font-height (with-current-buffer (window-buffer parent-window)
                        (posframe--get-font-height (point))))
```
This seems to work but I don't know much about posframe and whether is this the appropriate solution.

## Version:
This is as of version `20191108.745`

## Misc:
If you need a hydra-posframe to test (this is using pretty-hydra), you can use this to switch between window configs while keeping a posframe open (call `hydra-workspaces/body` to activate):
```
(pretty-hydra-define hydra-workspaces
  (:foreign-keys warn
   :title "Workspaces"
   :separator " "
   :quit-key "q")
  ("Navigate"
   (("r" eyebrowse-rename-window-config "rename" :exit t :column "Edit")
    ("c" eyebrowse-close-window-config "close")
    ("[" (eyebrowse-prev-window-config 1) "prev" :column "Navigation")
    ("]" (eyebrowse-next-window-config 1) "next"))
   "Jump"
   (("1" (eyebrowse-switch-to-window-config-1) "ws 1" :column "Quick Access")
    ("2" (eyebrowse-switch-to-window-config-2) "ws 2")
    ("3" (eyebrowse-switch-to-window-config-3) "ws 3")
    ("4" (eyebrowse-switch-to-window-config-4) "ws 4")
    ("5" (eyebrowse-switch-to-window-config-5) "ws 5")
    ("6" (eyebrowse-switch-to-window-config-6) "ws 6")
    ("7" (eyebrowse-switch-to-window-config-7) "ws 7")
    ("8" (eyebrowse-switch-to-window-config-8) "ws 8")
    ("9" (eyebrowse-switch-to-window-config-9) "ws 9"))))
```

**Comment by tumashu** [comment]
Please try again

**Comment by algoterranean** [comment]
Looks to be working. Thanks!

**Comment by tumashu** [comment]
ok
