### ISSUE TITLE
Width and Height do not work as documented in posframe-show

### ISSUE THREAD

**Issue by RBckmnn** [tumashu/posframe#58]
Hey there,

the commit d75dc1547a6a1cc2b385c736880eee77d7981aec changed the semantics of the WIDTH and HEIGTH arguments in calls to `posframe-show`. The docstring of the that function claims:

> Posframe's frame size can be set by WIDTH and HEIGHT.
If one of them is nil, posframe's frame size will fit the
buffer.  MIN-WIDTH and MIN-HEIGHT can be useful to prevent
posframe becoming too small.

However, the call to `fit-frame-to-buffer` introduced in the above commit will always fit the frame's size to the displayed buffer with the additional constraint that `MIN-WIDTH <= frame-width <= WIDTH` (and likewise for the frame's height). That change of behaviour led to this issue in doom emacs [Issue](https://github.com/hlissner/doom-emacs/issues/2540).

 Is posframe's code right now working as intended and has this issue to be resolved downstream or is this a bug in posframe?

**Comment by tumashu** [comment]
posframe will use fit-frame-to-buffer, so the document need update

**Comment by tumashu** [comment]
What value of your helm-display-buffer-default-height ?

```
(use-package! helm
  :after helm-mode
  :preface
  (setq helm-candidate-number-limit 50
        ;; Remove extraineous helm UI elements
        helm-display-header-line nil
        helm-mode-line-string nil
        helm-ff-auto-update-initial-value nil
        helm-find-files-doc-header nil
        ;; Default helm window sizes
        helm-display-buffer-default-width nil
        helm-display-buffer-default-height 0.25
        ;; When calling `helm-semantic-or-imenu', don't immediately jump to
        ;; symbol at point
        helm-imenu-execute-action-at-once-if-one nil
        ;; disable special behavior for left/right, M-left/right keys.
        helm-ff-lynx-style-map nil)
```

**Comment by tumashu** [comment]
what's the result (helm-posframe-get-size)

**Comment by tumashu** [comment]
我简化了一下 posframe 相关代码，看看行不行 https://github.com/tumashu/posframe/commit/b71b530ff73b56f956097d844db2cd66dc0e632b

**Comment by RBckmnn** [comment]
Hey,

I'm sorry that it has taken me so long to reply. The value of my helm-display-buffer-default-height is 0.25. Concerning helm-posframe... as far as I know, Doom emacs does not use helm-posframe and I have not installed it manually. But I'll try it out to see if it resolves my issue ;-).

**Comment by tumashu** [comment]
should fixed with new code
