### ISSUE TITLE
对单行文本的显示可能有问题？

### ISSUE THREAD

**Issue by cnsunyour** [tumashu/posframe#59]
最近在试用 emacs-rime 的时候发现偶尔会出现候选词显示不全的情况，如图： 
![image](https://user-images.githubusercontent.com/3713312/76722066-176fd780-677d-11ea-98c1-76823107ce1b.png)

因为换用 popup 方式显示正常，所以猜测可能与 posframe 有关。

在提 issue 讨论的过程中发现特定长度的字符串在 posframe 会有显示不全，如执行如下代码：
```
(posframe-show "*posframe-test"
               :string "ni ni ni ni ni| 1. 你妮好好妮好妮 2. 妮妮 3. 呢呢 4. 嶷嶷 5. 你  ")
```
最后的“你”不显示，如图：
![image](https://user-images.githubusercontent.com/3713312/76722113-3bcbb400-677d-11ea-9a84-e015fe2ed368.png)

此时在字符串中增加或删除一个字就都能全部显示，如删掉一个字：
![image](https://user-images.githubusercontent.com/3713312/76722141-57cf5580-677d-11ea-9026-6de48f36c096.png)

此时继续删字，删除到某个数量时又会出现显示不全：
![image](https://user-images.githubusercontent.com/3713312/76722156-69b0f880-677d-11ea-859f-dc791f1b57c3.png)

 此例共删除5个字后重现显示不全的情况，但是并没有找到规律，只是一个一个的尝试发现的。
不知是哪里的问题造成的。是调用的方式不对还是 posframe 在文本宽度计算上有问题？

又或者是我环境的问题？（有其他坛友也出现显示异常，但是表现形式和我的不一样，他的是把最后的空格给吃掉了）

我在 TG 群中请别的同学帮忙测试，有几位同学测试过后出现同样情况：
![image](https://user-images.githubusercontent.com/3713312/76722220-a250d200-677d-11ea-8bcb-3624defaed07.png)

![2020-03-16 12 00 14](https://user-images.githubusercontent.com/3713312/76722259-c8767200-677d-11ea-8e68-a83a477b98d1.jpg)

![2020-03-16 12 01 24](https://user-images.githubusercontent.com/3713312/76722294-e512aa00-677d-11ea-9888-c87eb3c57f3e.jpg)

不知其他人是否可以重现类似问题，方便的同学可以多试试不同长度的字符串是否会出现此问题。

**Comment by tumashu** [comment]
https://github.com/tumashu/posframe/commit/b71b530ff73b56f956097d844db2cd66dc0e632b 试试这个能不能解决问题

**Comment by cnsunyour** [comment]
好的，我试一下，尽快反馈结果，不过估计得需要几天时间才能确定是否还会复现问题。

**Comment by cnsunyour** [comment]
报告，经测还是有这个问题。复现方式：使用 emacs-rime 的 “地球拼音” 方案，输入编码 h ，然后向后翻页，我翻到第6页最后一个选项“合”后面的编码提示被“吃”掉了。

**Comment by tumashu** [comment]
posframe 调整窗口大小的功能已经完全依赖于 fit-frame-to-buffer， 按理说不应该出现此问题

**Comment by DogLooksGood** [comment]
如果 pyim 里面没有遇到这个问题的话，是不是有什么特别的处理技巧或需要注意的事呢?

**Comment by tumashu** [comment]
```
(setq rime-posframe-properties
      (list :internal-border-width 10
            :refresh 0.5))
```
试试这个设置，看是不是调整功能的代码由于 thread 被不小心跳过去了， 如果还不行，那估计就是 fit-frame-to-buffer 的bug 了

**Comment by DogLooksGood** [comment]
好像不行，也许就是 fit-frame-to-buffer 的 bug

**Comment by cnsunyour** [comment]
> ```
> (setq rime-posframe-properties
>       (list :internal-border-width 10
>             :refresh 0.5))
> ```
> 
> 试试这个设置，看是不是调整功能的代码由于 thread 被不小心跳过去了， 如果还不行，那估计就是 fit-frame-to-buffer 的bug 了

嗯，我进行此设置后再直接执行一楼的代码：
```emacs-lisp
(posframe-show "*posframe-test"
               :string "ni ni ni ni ni| 1. 你妮好好妮好妮 2. 妮妮 3. 呢呢 4. 嶷嶷 5. 你  ")
```
最后一个字没有显示。

**Comment by tumashu** [comment]
我在emacs28上测试，下面代码运行正常，估计 fit-frame-to-buffer 的问题修复了
```
(posframe-show "*posframe-test"
               :string "ni ni ni ni ni| 1. 你妮好好妮好妮 2. 妮妮 3. 呢呢 4. 嶷嶷 5. 你  ")
```

![图片](https://user-images.githubusercontent.com/67725/140009628-697ef0d4-5e31-4766-832a-35c9288988f1.png)

**Comment by tumashu** [comment]
另外一个法子就是自己计算 width，然后强制设置 :width，比如：
```
      (when doc
        (let* ((width
                (let ((n (apply #'max (mapcar #'string-width
                                              (split-string doc "\n+")))))
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                  (+ (min fill-column n) 1)))
               (height
                (max (+ company-tooltip-limit
                        (if company-posframe-show-indicator 1 0)
                        (if company-posframe-show-metadata 1 0))
                     (with-current-buffer company-posframe-buffer
                       (frame-height posframe--frame)))))
          (lower-frame
           (apply #'posframe-show
                  company-posframe-quickhelp-buffer
                  :string doc
                  :width width
                  :min-width width
                  :min-height height
                  :height height
                  :background-color (face-attribute 'company-posframe-quickhelp :background nil t)
                  :foreground-color (face-attribute 'company-posframe-quickhelp :foreground nil t)
                  company-posframe-quickhelp-show-params)))))))

```
