### ISSUE TITLE
posn-at-point is slow and called often

### ISSUE THREAD

**Issue by aaronjensen** [tumashu/posframe#6]
I noticed some typing lag and traced some of down to posframe calling `posn-at-point`. On my machine (macOS, emacs 27), each call can take 6-8ms and it is called at least twice with each keypress when using company-childframe. With fast typing it's called often and it can contribute to lag.

I experimented with naively memoizing it and it helped:

```elisp
(defvar posframe-previous-position nil)
(defvar posframe-previous-window nil)
(defun posn-at-point-memo (position window)
  (if (and (eq position posframe-previous-position)
           (eq window posframe-previous-window))
      posframe-previous-posn
    (setq posframe-previous-position position
          posframe-previous-window window
          posframe-previous-posn (posn-at-point position window))))
```

I'm sure there's a cleaner way to write that, but you get the idea 😄

**Comment by tumashu** [comment]
I  will test it after emacs26.1 release

**Comment by tumashu** [comment]
Maybe we should let posframe-poshandler-point-bottom-left-corner faster

**Comment by tumashu** [comment]
Please try the newest melpa version of posframe again,  it should more fast, maybe more bugs :-).

**Comment by aaronjensen** [comment]
So far so good, thanks. I'll let you know if I see any issues with it.
