### ISSUE TITLE
Ignore tab line by default

### ISSUE THREAD

**Issue by andreyorst** [tumashu/posframe#61]
> By default, posframe will display no header-line or mode-line. In case a header-line or mode-line is desired, users can set `RESPECT-HEADER-LINE` or `RESPECT-MODE-LINE` to `t`.

I think the same behavior should be applied to tab-line, because if `global-tab-line-mode` is set, the posframe also has tab-line, which is meaningless in most cases, I guess. `RESPECT-TAB-LINE` would be good to have.

**Comment by tumashu** [comment]
I use debian,  when I enable tab-bar-mode,   posframe do not show tab-bar

**Comment by andreyorst** [comment]
what would happen if you enable `global-tab-line-mode'?

вс, 26 апр. 2020 г., 07:37 tumashu <notifications@github.com>:

**Comment by tumashu** [comment]
have no tab-bar in posframe when global-tab-line-mode

**Comment by andreyorst** [comment]
For testing purposes I'm creating posframe with this command:

```emacs-lisp
(progn
  (posframe-hide-all)
  (posframe-show "*scratch*"
                 :poshandler 'posframe-poshandler-point-top-left-corner))
```

This is the result I see:

![image](https://user-images.githubusercontent.com/19470159/80300486-eafca180-87a5-11ea-95b6-09656ed9ecb9.png)

Thisi is `emacs -q`.

**Comment by tumashu** [comment]
/home/feng/图片/截图_2020-04-26_16-07-00.png

**Comment by tumashu** [comment]
![截图_2020-04-26_16-07-00](https://user-images.githubusercontent.com/67725/80301678-113b3500-87d8-11ea-9f76-a926a8fd7b1f.png)

**Comment by tumashu** [comment]
I have tested you code, have the same problem

**Comment by tumashu** [comment]
should fixed

**Comment by andreyorst** [comment]
Yes, seems to work now. Thanks!
