### ISSUE TITLE
[feature request] provide poshandler which places bottom left above the point

### ISSUE THREAD

**Issue by yyoncho** [tumashu/posframe#66]
This is what most natural placement what most of the application needs.

Here it is screenshot from vscode: 
![Screenshot](https://user-images.githubusercontent.com/13259670/86237902-46cc1800-bba5-11ea-8031-8fef295926bd.png)

It will be even better if this handler alternates the placement of the frame when there is no enough place above the cursor.

**Comment by tumashu** [comment]
good idea.

**Comment by tumashu** [comment]
try: posframe-poshandler-point-bottom-left-corner-upward

**Comment by yyoncho** [comment]
Thank you, seems like it is working fine.

**Comment by tumashu** [comment]
ok
