### ISSUE TITLE
posframe should not reject focus unconditionally.

### ISSUE THREAD

**Issue by yyoncho** [tumashu/posframe#67]
Accepting the focus is something that is needed for some cases. This could be handled by a parameter in show method which posframe--redirect-posframe-focus will check.

**Comment by tumashu** [comment]
focus seem to have more unexpect bugs, hard to deal with  :-(

**Comment by yyoncho** [comment]
> focus seem to have more unexpect bugs, hard to deal with :-(

Are those reported in the upstream?

What I want to implement is on hover for a variable when debugging and allow clicking in the popup and expanding the value.

**Comment by tumashu** [comment]
Please test this branch: https://github.com/tumashu/posframe/pull/68

**Comment by yyoncho** [comment]
seems to be working fine, thank you! 

Here it is is the intermediate result: https://files.gitter.im/58f7934fd73408ce4f5980dc/9N0r/Peek-2020-07-30-23-18.mp4

**Comment by tumashu** [comment]
ok, merged to master
