### ISSUE TITLE
[Feature request] provide argument which will cause posframe to hide when user switches  the buffer

### ISSUE THREAD

**Issue by yyoncho** [tumashu/posframe#69]
we are about to use posframe in 3 packages - lsp-ui, dap-mode, lsp-mode and we have that same repeating code(probably other packages that use posframe will benefit as well) so it seems like it will be better placed in `posframe` project.

(cc @ericdallo )

**Comment by tumashu** [comment]
like this?
```
(add-hook 'buffer-list-update-hook #'test)

(defun test ()
  (let ((buffer-list-update-hook nil))
    (posframe-hide-all)))
```

**Comment by yyoncho** [comment]
This will hide popup even when something like `(with-temp-buffer` is executed. Something like that should do:

```
(let ((current-buffer (current-buffer)))
  (add-hook 'post-command-hook 
            (lambda ()
              (unless (eq (current-buffer) current-buffer )
                (posframe-hide-that-particular-frame)
                ... ;; cleanup hook
                ))))
```

**Comment by tumashu** [comment]
@yyoncho Please test this branch.

**Comment by yyoncho** [comment]
Hm - we will need that for multiple frames at the same time like this - https://youtu.be/7BODBLwgw1s so maybe posframe--buffer should be a buffer.

Also, seems like it will be better to unsubscribe from post-command-hook when deleting frame and resubscribe when a new frame bound to buffer is created.

**Comment by tumashu** [comment]
sorry, i can not open this link for some reason, 

"posframe--buffer should be a buffer."

posframe--buffer can be a buffer or buffer-name

"Also, seems like it will be better to unsubscribe from post-command-hook when deleting frame and resubscribe when a new frame bound to buffer is created."

any benefit to do like this？

**Comment by yyoncho** [comment]
> posframe--buffer can be a buffer or buffer-name

What I meant that we will be doing 

```
(posframe-show "frame1" ...)
(posframe-show "frame2" ...)
```

with the code as it is it will hide only the second one when you switch the buffer.

> any benefit to do like this？

Performance - post-command-hook is called thousands of times per single emacs session.

**Comment by tumashu** [comment]
@yyoncho Please try this https://github.com/tumashu/posframe/commit/c702898c7123c8d466caba8d490237fe2738aa90

**Comment by yyoncho** [comment]
Everything works, thanks. It will be great if attachment to the post-command-hook can be removed from the top level.

**Comment by tumashu** [comment]
It will be great if attachment to the post-command-hook can be removed from the top level.

why need remove？ if remove, the posframe feature will broken.

dynamic managing post-command-hook by posframe is not a good idea in my opinion,
for it make posframe's code more complicate
