### ISSUE TITLE
[Feature Request] allow reusing frames in more cases.

### ISSUE THREAD

**Issue by yyoncho** [tumashu/posframe#71]
ATM the frame is reused if the last displayed frame has been created with the same set of parameters. This is very limiting for the cases when there are multiple extensions using posframe(e. g. helm-posframe, company-posframe) the frames are recreated too often and this results in poor behavior.

Proposed fix:

Introduce a flag - keep-frame. posframe will handle that flag by storing the frame in a lookup by buffer-id.

**Comment by tumashu** [comment]
I do not understand this feature, posframe always reuse child-frame, only if it has to recreate, keep-frame seem to needless.

**Comment by tumashu** [comment]
reuse is controled by list

（list parent-frame
                    foreground-color
                    background-color
                    right-fringe
                    left-fringe
                    internal-border-width
                    font
                    keep-ratio
                    override-parameters
                    respect-header-line
                    respect-mode-line
                    respect-tab-line
                    accept-focus)

**Comment by yyoncho** [comment]
Hm, I think that I might be seeing a helm-posframe bug. I will take a look more closely and let you know

**Comment by yyoncho** [comment]
To elaborate - with helm-posframe the frame seems to be recreated on each invocation.

**Comment by yyoncho** [comment]
Closing. I will open issue in helm-posframe.
