### ISSUE TITLE
Wery strange bug with combination of scrolling, treemacs, and emacs-parinfer-mode

### ISSUE THREAD

**Issue by andreyorst** [tumashu/posframe#72]
Hi, this is really strange, but combination of posframe, treemacs, and parinfer-rust-mode, produces weird behavior. Reverting last commit fixes it.

What exactly happens:

- I open lisp file with parinfer mode enabled
- I have treemacs window on the left side of Emacs
- I scroll upwards
- Buffer window disappears, and treemacs window is used instead

Here's a recording:  [bug.zip](https://github.com/tumashu/posframe/files/5070882/bug.zip)

Reverting 04b91d5 fixes the issue.

---

It seems that posframe adds new post command hook, that accidentially runs after scrolling and hides current window instead of posframe one.

https://github.com/tumashu/posframe/blob/04b91d507ba8509a43aa268cc8cdd3a190e05849/posframe.el#L837-L852

**Comment by tumashu** [comment]
I do not understand why, this hook hide frame instead of window, and check posframe-parent-buffer  frame-para, current frame can not have this para

**Comment by tumashu** [comment]
please test:
1. parinfer-rust-mode disable and try
2. close treemacs and try
3. close two and try

**Comment by andreyorst** [comment]
> please test:
> 
>     1. parinfer-rust-mode disable and try
> 
>     2. close treemacs and try
> 
>     3. close two and try

I had a pretty long debugging session yesterday as I've updated all my packages, and this bug appeared, so I've reverted everything and started upgrading one package at a time and checking. Upgrading posframe triggered this issue. Then I've reverted everything again and updated just the posframe package, and bug persisted. 

Disabling parinfer mode also make this issue not happen, so perhaps parinfer's post command hook interferes with posframe's somehow.  But this wasn't happening until recent posframe update.

After this bug happens Emacs is in unusable state,. as every frame related command messages, that there are two windows which are actually the same.

**Comment by tumashu** [comment]
Eval the below three version hook function, see which one can tragger the bug,
by the way , you can (remove-hook 'post-command-hook #'posframe-run-hidehandler)
to temp deal with this problem.

```
(defun posframe-run-hidehandler ()
  "Run posframe hidehandler. this function is used in `post-command-hook'."
  (while-no-input
    (redisplay)
    t
    ;; (dolist (frame (frame-list))
    ;;   (let ((hidehandler (frame-parameter frame 'posframe-hidehandler))
    ;;         (buffer (frame-parameter frame 'posframe-buffer))
    ;;         (parent-buffer (frame-parameter frame 'posframe-parent-buffer)))
    ;;     (when (and hidehandler
    ;;                (funcall hidehandler
    ;;                         (list
    ;;                          :posframe-buffer buffer
    ;;                          :posframe-parent-buffer parent-buffer)))
    ;;       (posframe--make-frame-invisible frame))))
    ))


(defun posframe-run-hidehandler ()
  "Run posframe hidehandler. this function is used in `post-command-hook'."
  (while-no-input
    (redisplay)
    (dolist (frame (frame-list))
      ;; (let ((hidehandler (frame-parameter frame 'posframe-hidehandler))
      ;;       (buffer (frame-parameter frame 'posframe-buffer))
      ;;       (parent-buffer (frame-parameter frame 'posframe-parent-buffer)))
      ;;   (when (and hidehandler
      ;;              (funcall hidehandler
      ;;                       (list
      ;;                        :posframe-buffer buffer
      ;;                        :posframe-parent-buffer parent-buffer)))
      ;; (posframe--make-frame-invisible frame)))
      )))

(defun posframe-run-hidehandler ()
  "Run posframe hidehandler. this function is used in `post-command-hook'."
  (while-no-input
    (redisplay)
    (dolist (frame (frame-list))
      (let ((hidehandler (frame-parameter frame 'posframe-hidehandler))
            (buffer (frame-parameter frame 'posframe-buffer))
            (parent-buffer (frame-parameter frame 'posframe-parent-buffer)))
        ;; (when (and hidehandler
        ;;            (funcall hidehandler
        ;;                     (list
        ;;                      :posframe-buffer buffer
        ;;                      :posframe-parent-buffer parent-buffer)))
        ;;   (posframe--make-frame-invisible frame))
        )
      )))

```

**Comment by tumashu** [comment]
try this version too
```
(defun posframe-run-hidehandler ()
  "Run posframe hidehandler. this function is used in `post-command-hook'."
  (ignore-errors
    (dolist (frame (visible-frame-list))
      (let ((hidehandler (frame-parameter frame 'posframe-hidehandler))
            (buffer (frame-parameter frame 'posframe-buffer))
            (parent-buffer (frame-parameter frame 'posframe-parent-buffer)))
        (when (and hidehandler
                   (funcall hidehandler
                            (list
                             :posframe-buffer buffer
                             :posframe-parent-buffer parent-buffer)))
          (posframe--make-frame-invisible frame))))))

(add-hook 'post-command-hook #'posframe-run-hidehandler)

```

**Comment by andreyorst** [comment]
there's no presence of this bug with the latest function

**Comment by andreyorst** [comment]
And actually addith this as a post command hook triggers the issue:
```emacs-lisp
(defun posframe-run-hidehandler ()
  "Run posframe hidehandler. this function is used in `post-command-hook'."
  (while-no-input
    (redisplay)
    t))
```

**Comment by tumashu** [comment]
Should be fixed, parinfer maybe a special mode, so it may conflite with while-no-input

**Comment by andreyorst** [comment]
Doesn't seem to happen with b282107 applied. Thanks for the fix! I'll make parinfer-rust-mode maintainer aware of this, for further investigation
