### ISSUE TITLE
Add the option to disable focus redirection

### ISSUE THREAD

**Issue by jwijenbergh** [tumashu/posframe#76]
I am creating a package that uses posframe to create child frames which need focus. Setting `posframe-mouse-banish` to `nil` and `:accept-focus t` already works as expected.

[However, due to the following line](https://github.com/tumashu/posframe/blob/7b92a54e588889a74d36d51167e067676db7be8a/posframe.el#L693) focus can be redirected when emacs is e.g. refocused. Is it possible to disable this hook for certain child frames? I am currently using `advice-add` with `:after` for `posframe--redirect-posframe-focus` to redirect the focus back to the child frame but this is not a neat solution.

**Comment by tumashu** [comment]
maybe we can do like: when accept-focus is t, do not redirect posframe focus

**Comment by jwijenbergh** [comment]
> maybe we can do like: when accept-focus is t, do not redirect posframe focus

I think that would be a good solution

**Comment by tumashu** [comment]
Please try this branch.

**Comment by jwijenbergh** [comment]
> Please try this branch.

Works as expected!

**Comment by tumashu** [comment]
ok

**Comment by tumashu** [comment]
merged

**Comment by jwijenbergh** [comment]
Thanks for the quick response!
