### ISSUE TITLE
Ignore tab bar by default

### ISSUE THREAD

**Issue by zhmars** [tumashu/posframe#79]
Similar to  #61,  same behavior should be applied to tab-bar.

For now,  when tab bar enabled, it looks like:
![2020-10-23 19-44-29屏幕截图](https://user-images.githubusercontent.com/18466397/96999712-37177b80-1568-11eb-95b0-e7b146c3a744.png)

### To reproduce:

- run `emacs -Q` and then eval these code:

```elisp
(tab-bar-mode t)

(add-to-list 'load-path "~/.emacs.d/package/elpa/posframe-20201009.946")

(require 'posframe)
(when (posframe-workable-p)
  (posframe-show " *my-posframe-buffer*"
                :string "This is a test"
                :position (point)))
```

**Comment by tumashu** [comment]
should be fixed, please test again

**Comment by zhmars** [comment]
> should be fixed, please test again

Confirmed. Thanks!
