### ISSUE TITLE
Custom poshandlers

### ISSUE THREAD

**Issue by richardfeynmanrocks** [tumashu/posframe#82]
This is potentially a mix of an issue and a feature request. When trying to define my own poshandler with the result of an expression, the predicate `fixnump` is violated when the posframe position is set.

For example the following test poshandler
```elisp
(defun temp-poshandler (_info)
    '(-15 . (+ 15 (* 90 2))))
```
gives this error when applied to a posframe
```
posframe--set-frame-position: Wrong type argument: fixnump, (+ 15 (* 90 2))
```

Ideally, there'd be a builtin poshandler that takes an absolute x and y value within the frame and displayed a posframe at that location (and also wouldn't have strange fixnump violations for the results of integer expressions, although as I'm relatively new to Emacs Lisp I may be messing something up on my end).

**Comment by tumashu** [comment]
what about this:
```
(defun temp-poshandler (_info)
  (cons -15  (+ 15 (* 90 2))))
```

**Comment by richardfeynmanrocks** [comment]
That works perfect, had a feeling I was missing something basic. Thank you for your time!
