### ISSUE TITLE
fail to initialize Org-mode in posframe

### ISSUE THREAD

**Issue by randomwangran** [tumashu/posframe#83]
Dear the maintainers of posframe:

Thank for writing this package, I use ivy-posframe everyday and
enjoy using it.

I am writing this issue because that I try to insert a standard
Org-mode link into posframe. I've searched the issue but could not
find anything related to it.

Following is a simple example.

 ```elisp
(setq my-posframe-buffer " *my-posframe-buffer*")

(with-current-buffer (get-buffer-create my-posframe-buffer)
  (erase-buffer)
  (insert "* [[Org-mode link]]")
  (org-mode))

(when (posframe-workable-p)
  (posframe-show my-posframe-buffer
                 :position (point)))
```

What I want to do is to insert a standard Org-mode link in posframe,
but it only shows the plain text on my side.

I was wondering that if this is achievable in posframe?

Thank you.

**Comment by tumashu** [comment]
I have tested with your code, and work,  maybe you can test with  emacs -Q :-)

file:///home/feng/%E6%A1%8C%E9%9D%A2/%E6%88%AA%E5%9B%BE_2020-12-21_09-11-07.png

**Comment by randomwangran** [comment]
That's amazing! I will test it and report it later.

**Comment by randomwangran** [comment]
I've tested with `emacs -q` but it does not repeat your screen.

Emacs, OS info, and desktop info are shown in the following figure.

![image](https://user-images.githubusercontent.com/8197831/102818090-f5a42080-439e-11eb-802b-73c9939b6c53.png)

**Comment by randomwangran** [comment]
If the buffer name is not start with " \* ", Org-mode can be initialize, as the discussion in emacs-china.org.

Thanks for your help.
