### ISSUE TITLE
void-function  fit-frame-to-buffer-1

### ISSUE THREAD

**Issue by jueqingsizhe66** [tumashu/posframe#86]
(defun posframe--fit-frame-to-buffer (posframe height min-height width min-width)
  ;; This only has effect if the user set the latter var to `hide'.
  (let ((x-gtk-resize-child-frames posframe-gtk-resize-child-frames))
    (fit-frame-to-buffer-1
     posframe height min-height width min-width nil nil nil)))

**Comment by corrafig** [comment]
This broke posframe in my Doom Emacs :(

**Comment by tumashu** [comment]
please try again

**Comment by corrafig** [comment]
Works again in 27.1. Thank you @tumashu for quick fix.

**Comment by jueqingsizhe66** [comment]
Works again, thanks
![Uploading notDefined.png…]()

**Comment by firmart** [comment]
Don't know why, but I got `posframe--fit-frame-to-buffer: Symbol’s function definition is void: fit-frame-to-buffer-1` under `GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.20, cairo version 1.16.0) of 2020-10-16`
