### ISSUE TITLE
Emacs 28 is bringing breaking changes

### ISSUE THREAD

**Issue by aaronjensen** [tumashu/posframe#89]
> ** New face 'child-frame-border' and frame parameter 'child-frame-border-width'.
> The face and width of child frames borders can now be determined
> separately from those of normal frames.  To minimize backward
> incompatibility, child frames without a 'child-frame-border-width'
> parameter will fall back to using 'internal-border-width'.  However,
> the new 'child-frame-border' face does constitute a breaking change
> since child frames' borders no longer use the 'internal-border' face.

**Comment by tumashu** [comment]
wow, big change :-)

**Comment by tumashu** [comment]
please test this branch

**Comment by tumashu** [comment]
合并到 master 了，试试吧

**Comment by aaronjensen** [comment]
It looks like it works well for me, thank you. It fixes all downstream packages without me having to resort to any hacks.
