### ISSUE TITLE
sdcv 顶部有未知padding

### ISSUE THREAD

**Issue by manateelazycat** [tumashu/posframe#93]
![2021-03-03 09-04-04屏幕截图](https://user-images.githubusercontent.com/237487/109736692-b47e8700-7bff-11eb-9afc-5810111aa5ea.png)
不知道为什么顶部有未知 padding ？
以前没有这个padding

sdcv里面posframe参数截图里面有。

麻烦大佬帮忙参谋下。 ;)

**Comment by tumashu** [comment]
看起来也不像空行

```
(posframe-show "aaa"
               :string "This is a test"
               :tab-line-height 0
               :header-line-height 0
               )
```
这个什么反应？

**Comment by manateelazycat** [comment]
Fix by https://github.com/tumashu/posframe/pull/94
